import os
from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer

def start_server():
    # 1. Ensure the shared directory exists
    shared_dir = "./shared_vault"
    if not os.path.exists(shared_dir):
        os.makedirs(shared_dir)
        print(f"Created shared directory: {shared_dir}")
        print("Please place your .vault files generated by crypto_engine.py into this folder.")
        
    # 2. Instantiate a dummy authorizer for managing 'virtual' users
    authorizer = DummyAuthorizer()

    # 3. Define a new user having full r/w permissions
    # User: 'aryaditya', Password: 'vit', pointing to our secure vault folder
    authorizer.add_user("aryaditya", "vit", shared_dir, perm="elradfmwMT")

    # 4. Instantiate FTP handler class
    handler = FTPHandler
    handler.authorizer = authorizer

    # 5. Define a customized banner (string returned when client connects)
    handler.banner = "Aegis-Hotspot Vault FTP Server Ready."

    # 6. Bind to 0.0.0.0 (all interfaces, making it available on the Hotspot) at port 2121
    address = ("0.0.0.0", 2121)
    server = FTPServer(address, handler)

    # 7. Start limits (prevent resource exhaustion)
    server.max_cons = 256
    server.max_cons_per_ip = 5

    # 8. Start serving
    print(f"Starting FTP server on {address[0]}:{address[1]}...")
    print("Listening for authenticated connections from Termux...")
    server.serve_forever()

if __name__ == "__main__":
    start_server()
